config/routes.rb
Openmeetup::Application.routes.draw do

  # mount WillFilter::Engine => '/will_filter'
  # mount Tr8n::Engine => '/tr8n'

  mount AdminMailer::Preview => '/admin_mailer/mail_view'
  mount CommentMailer::Preview => '/comment_mailer/mail_view'
  mount EventInvitationMailer::Preview => '/event_invitation_mailer/mail_view'
  mount EventMailer::Preview => '/event_mailer/mail_view'
  mount FriendshipMailer::Preview => '/friendship_mailer/mail_view'
  mount GroupInvitationMailer::Preview => '/group_invitation_mailer/mail_view'
  mount GroupMailer::Preview => '/group_mailer/mail_view'
  mount LetterMailer::Preview => '/letter_mailer/mail_view'
  mount MinionMailer::Preview => '/minion_mailer/mail_view'
  mount MembershipRequestMailer::Preview => '/membership_request_mailer/mail_view'
  mount ParticipationMailer::Preview => '/participation_mailer/mail_view'
  mount PostMailer::Preview => '/post_mailer/mail_view'
  mount UserMailer::Preview => '/user_mailer/mail_view'
  mount VoteMailer::Preview => '/vote_mailer/mail_view'
  mount WaveMailer::Preview => '/wave_mailer/mail_view'

  namespace :admin do
    resources :users
  end

  resources :activities do
    resources :comments, shallow: true
  end

  resources :cities do
    member do
      get :search
    end
    collection do
      post :jump
    end
  end

  resources :feedbacks

  resources :friendships do
    member do
      post :decline
      post :set_confirmed
      post :set_delayed
    end
  end

  resources :groups do
    member do
      get :events
      get :images
      get :invited
      get :members
      get :requested_members
      post :set_image
      post :set_header
      get :tags
      get :waves
    end
    resources :posts, shallow: true
    resources :events, shallow: true do
      member do
        get :actual
        get :images
        get :invited
        get :map
        get :participations
        get :reviews
        get :users
        get :users_with_emails
      end
      resources :absences, shallow: true do
        collection do
          get :set
        end
      end
      resources :comments, shallow: true
      resources :event_invitations, shallow: true
      resources :images, shallow: true do
        collection do
          post :upload
        end
      end
      resources :participations, shallow: true do
        member do
          post :checkin
        end
        collection do
          get :set
        end
      end
      resources :posts, shallow: true
      resources :questions, shallow: true
      resources :reviews, shallow: true
    end
    resources :group_invitations, shallow: true
    resources :images, shallow: true do
      collection do
        post :upload
      end
    end
    resources :membership_requests, shallow: true do
      member do
        put :confirm
      end
    end
    resources :memberships, shallow: true do
      collection do
        get :set
      end
      member do
        put :set_admin
        put :unset_admin
      end
    end
    resources :tags, shallow: true do
      resources :taggings, shallow: true do
        collection do
          post :set
        end
      end
    end
  end

  resources :images do
    member do
      get :next
      get :previous
    end
    resources :comments, shallow: true
  end

  resources :interests do
    resources :interest_taggings, shallow: true
  end

  resources :letter_templates do
    member do
      post :create_letter
    end
  end

  resources :letters do
    member do
      post :mail
      post :mailtest
    end
  end

  resources :notifications

  resources :passwords

  resources :posts do
    resources :comments, shallow: true
  end

  resources :settings

  resources :tags

  resources :uninterests, only: [:index, :create, :destroy]

  resource :user_sessions

  resources :users do
    resources :friendships, shallow: true
    collection do
      get :request_invite
      get :recommendations
      get :validate_email
    end
    member do
      get :calendar
      get :edit_city
      get :facebook_groups
      get :friend_requests
      get :groups
      get :set_admin
      post :set_admin
      get :unset_admin
      post :unset_admin
      post :set_avatar
      post :set_header
      get :settings
      get :tags
      get :waves
    end
  end

  resources :votes, only: [:index] do
    collection do
      post :set
    end
  end

  resources :waves do
    resources :wave_items
  end

  match '/about' => 'root#about', as: :about
  match '/crash' => 'root#crash', as: :crash
  match '/search' => 'search#index', as: :search
  match '/restricted_access' => 'root#restricted_access', as: :restricted_access
  match '/terms' => 'root#terms', as: :terms
  match '/pricing' => 'root#pricing', as: :pricing
  match '/privacy' => 'root#privacy', as: :privacy

  match '/discovery' => 'discovery#index', as: :discovery

  match '/system-settings' => 'dashboard#index', as: :system
  match '/reload' => 'dashboard#reload', as: :reload
  match '/download_database' => 'dashboard#download_database', as: :download_database
  match '/download_translations' => 'dashboard#download_translations', as: :download_translations

  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'
  match '/sign_in' => 'root#sign_in', as: :sign_in
  match '/sign_in_with_email' => 'users#new', as: :sign_in_with_email
  match '/sign_out' => 'user_sessions#destroy', as: :sign_out

  root to: 'root#index'
  match ':controller(/:action(/:id))(.:format)'
  match '/:id' => 'root#undefined', as: :undefined
end

app/models/membership.rb
# encoding: UTF-8

class Membership < ActiveRecord::Base
  key :is_admin, as: :boolean
  timestamps

  belongs_to :user, counter_cache: true
  belongs_to :group, counter_cache: true

  has_many :activities, as: :activable, dependent: :destroy

  attr_protected :is_admin

  after_create do
    group.admins.each do |user|
      GroupMailer.join(self, user).deliver if user.email
    end
    Activity.create_from self, user, group
  end
end

Membership.auto_upgrade!

app/controllers/memberships_controller.rb
# encoding: UTF-8

class MembershipsController < CommonController
  load_resource :group
  load_resource :membership, through: :group, shallow: true
  authorize_resource except: [:set]
  before_filter :set_add_membership_for, only: [:set]
  before_filter :authenticate, only: [:set]

  def index
    redirect_to @group
  end

  def show
    redirect_to @group
  end


  def create
    unless @group.membership_for(current_user)
      @membership.save
      cookies.delete :add_membership_for
    end
    flash[:code] = "modalbox.create('#{tags_group_url(@group)}')" if @group.tags.size > 0
    redirect_to @group
  end

  def destroy
    unless @membership.is_admin? and @membership.group.admins.count > 1
      @membership.destroy
      if request.xhr?
        render :create
      else
        redirect_to @membership.group
      end
    else
      redirect_to @membership.group, alert: 'Nem törölheted magad, ha nincsen legalább két admin!'
    end
  end

  def set
    @membership = @group.memberships.build
    create
  end

  def set_admin
    @membership.is_admin = true
    @membership.save
    redirect_to members_group_url(@membership.group)
  end

  def unset_admin
    @membership.is_admin = false
    @membership.save
    redirect_to members_group_url(@membership.group)
  end

protected

  def set_add_membership_for
    cookies[:add_membership_for] = @group.id
  end
end

app/views/memberships/_button.html.slim
- if membership = group.membership_for(current_user) and can? :destroy, membership
  .btn-group.pull-right
    a.btn.btn-success.dropdown-toggle(data-toggle="dropdown" href="#")
      =' %{<i class="icon-ok-sign icon-black"></i> #{tr('Joined')}}.html_safe
      span.caret
    ul.dropdown-menu
      li= link_to tr('Leave group'), membership, method: :delete

- elsif group.is_closed?
  - if membership_request = group.membership_request_for(current_user)
    =' button_to %{<i class="icon-ok-sign icon-white"></i> #{tr('Requested membership')}}.html_safe, membership_request, method: :delete, class: 'btn btn-default'
  - else
    =' button_to %{<i class="icon-plus-sign icon-white"></i> #{tr('Request membership')}}.html_safe, group_membership_requests_path(group), method: :post, class: 'btn btn-primary'
- else
  =' button_to %{<i class="icon-plus-sign icon-white"></i> #{tr('Join')}}.html_safe, group_memberships_path(group), method: :post, class: 'btn btn-primary'

app/views/memberships/_membership.html.haml
= div_for membership.user do
  - if can? :destroy, membership
    .pull-right= link_to 'Törlés', membership, :method => :delete, :confirm => 'Biztosan törlöd?', :class => 'btn btn-danger btn-small'
  .avatar= user_avatar membership.user
  = link_to membership.user.name, membership.user

app/views/memberships/_membership.html.slim
= div_for membership.user, class: 'list_item avatar_item clearfix' do
  .button-menu
    - if can? :destroy, membership
      = button_to tr('Remove'), membership, method: :delete, confirm: trl('Are you sure?'), class: 'btn btn-danger btn-xs'
    - if can? :set_admin, membership and not membership.group.admins.include?(membership.user)
      = button_to tr('Set admin'), set_admin_membership_path(membership), method: :put, confirm: trl('Are you sure?'), class: 'btn btn-default btn-xs'
    - if can? :unset_admin, membership and membership.group.admins.include?(membership.user)
      = button_to tr('Remove admin'), unset_admin_membership_path(membership), method: :put, confirm: trl('Are you sure?'), class: 'btn btn-danger btn-xs'
  .avatar= user_avatar membership.user
  =' link_to membership.user.name, membership.user
  - if membership.is_admin?
    span.label.label-danger=' tr('group admin')
  span.date= l membership.created_at

app/views/memberships/create.js.erb
$('#membership_button_for_group_<%= @membership.group.id %>').replaceWith('<%= escape_javascript(render('memberships/button', group: @membership.group)) %>')
<% if @membership.frozen? -%>
  $('#membership_button_for_group_<%= @membership.group.id %>').closest('.group').removeClass('membered').find('span.members').html('<%= @membership.group.members.size %>')
<% else %>
  $('#membership_button_for_group_<%= @membership.group.id %>').closest('.group').addClass('membered').find('span.members').html('<%= @membership.group.members.size %>')
<% end%>