config/routes.rb
Openmeetup::Application.routes.draw do

  # mount WillFilter::Engine => '/will_filter'
  # mount Tr8n::Engine => '/tr8n'

  mount AdminMailer::Preview => '/admin_mailer/mail_view'
  mount CommentMailer::Preview => '/comment_mailer/mail_view'
  mount EventInvitationMailer::Preview => '/event_invitation_mailer/mail_view'
  mount EventMailer::Preview => '/event_mailer/mail_view'
  mount FriendshipMailer::Preview => '/friendship_mailer/mail_view'
  mount GroupInvitationMailer::Preview => '/group_invitation_mailer/mail_view'
  mount GroupMailer::Preview => '/group_mailer/mail_view'
  mount LetterMailer::Preview => '/letter_mailer/mail_view'
  mount MinionMailer::Preview => '/minion_mailer/mail_view'
  mount MembershipRequestMailer::Preview => '/membership_request_mailer/mail_view'
  mount ParticipationMailer::Preview => '/participation_mailer/mail_view'
  mount PostMailer::Preview => '/post_mailer/mail_view'
  mount UserMailer::Preview => '/user_mailer/mail_view'
  mount VoteMailer::Preview => '/vote_mailer/mail_view'
  mount WaveMailer::Preview => '/wave_mailer/mail_view'

  namespace :admin do
    resources :users
  end

  resources :activities do
    resources :comments, shallow: true
  end

  resources :cities do
    member do
      get :search
    end
    collection do
      post :jump
    end
  end

  resources :feedbacks

  resources :friendships do
    member do
      post :decline
      post :set_confirmed
      post :set_delayed
    end
  end

  resources :groups do
    member do
      get :events
      get :images
      get :invited
      get :members
      get :requested_members
      post :set_image
      post :set_header
      get :tags
      get :waves
    end
    resources :posts, shallow: true
    resources :events, shallow: true do
      member do
        get :actual
        get :images
        get :invited
        get :map
        get :participations
        get :reviews
        get :users
        get :users_with_emails
      end
      resources :absences, shallow: true do
        collection do
          get :set
        end
      end
      resources :comments, shallow: true
      resources :event_invitations, shallow: true
      resources :images, shallow: true do
        collection do
          post :upload
        end
      end
      resources :participations, shallow: true do
        member do
          post :checkin
        end
        collection do
          get :set
        end
      end
      resources :posts, shallow: true
      resources :questions, shallow: true
      resources :reviews, shallow: true
    end
    resources :group_invitations, shallow: true
    resources :images, shallow: true do
      collection do
        post :upload
      end
    end
    resources :membership_requests, shallow: true do
      member do
        put :confirm
      end
    end
    resources :memberships, shallow: true do
      collection do
        get :set
      end
      member do
        put :set_admin
        put :unset_admin
      end
    end
    resources :tags, shallow: true do
      resources :taggings, shallow: true do
        collection do
          post :set
        end
      end
    end
  end

  resources :images do
    member do
      get :next
      get :previous
    end
    resources :comments, shallow: true
  end

  resources :interests do
    resources :interest_taggings, shallow: true
  end

  resources :letter_templates do
    member do
      post :create_letter
    end
  end

  resources :letters do
    member do
      post :mail
      post :mailtest
    end
  end

  resources :notifications

  resources :passwords

  resources :posts do
    resources :comments, shallow: true
  end

  resources :settings

  resources :tags

  resources :uninterests, only: [:index, :create, :destroy]

  resource :user_sessions

  resources :users do
    resources :friendships, shallow: true
    collection do
      get :request_invite
      get :recommendations
      get :validate_email
    end
    member do
      get :calendar
      get :edit_city
      get :facebook_groups
      get :friend_requests
      get :groups
      get :set_admin
      post :set_admin
      get :unset_admin
      post :unset_admin
      post :set_avatar
      post :set_header
      get :settings
      get :tags
      get :waves
    end
  end

  resources :votes, only: [:index] do
    collection do
      post :set
    end
  end

  resources :waves do
    resources :wave_items
  end

  match '/about' => 'root#about', as: :about
  match '/crash' => 'root#crash', as: :crash
  match '/search' => 'search#index', as: :search
  match '/restricted_access' => 'root#restricted_access', as: :restricted_access
  match '/terms' => 'root#terms', as: :terms
  match '/pricing' => 'root#pricing', as: :pricing
  match '/privacy' => 'root#privacy', as: :privacy

  match '/discovery' => 'discovery#index', as: :discovery

  match '/system-settings' => 'dashboard#index', as: :system
  match '/reload' => 'dashboard#reload', as: :reload
  match '/download_database' => 'dashboard#download_database', as: :download_database
  match '/download_translations' => 'dashboard#download_translations', as: :download_translations

  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'
  match '/sign_in' => 'root#sign_in', as: :sign_in
  match '/sign_in_with_email' => 'users#new', as: :sign_in_with_email
  match '/sign_out' => 'user_sessions#destroy', as: :sign_out

  root to: 'root#index'
  match ':controller(/:action(/:id))(.:format)'
  match '/:id' => 'root#undefined', as: :undefined
end

app/models/group.rb
# encoding: UTF-8

class Group < ActiveRecord::Base
  key :name
  key :permaname, index: true
  key :permalink, index: true
  key :description, as: :text
  key :creation_letter_text, as: :text
  key :facebook_uid
  key :location, index: true
  key :image_file_name
  key :image_content_type
  key :image_file_size, as: :integer
  key :image_updated_at, as: :datetime
  key :header_file_name
  key :header_content_type
  key :header_file_size, as: :integer
  key :header_updated_at, as: :datetime
  key :is_closed, as: :boolean, default: false
  key :url
  key :facebook_url
  timestamps
  key :memberships_count, as: :integer, default: 0

  belongs_to :city
  belongs_to :language
  belongs_to :user
  has_many :activities, dependent: :destroy
  has_many :admins, through: :memberships, source: :user, conditions: {'memberships.is_admin' => true}
  has_many :events, dependent: :destroy
  has_many :group_invitations, dependent: :nullify
  has_many :group_taggings, dependent: :destroy
  has_many :images, as: :imageable
  has_many :membership_requests, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, source: :user
  has_many :notifications, dependent: :destroy
  has_many :posts, as: :postable, dependent: :destroy
  has_many :requested_members, through: :membership_requests, source: :user
  has_many :reviews, dependent: :destroy
  has_many :tags, through: :group_taggings
  has_many :waves, dependent: :nullify

  attr_reader :tag_tokens

  has_attached_file :header,
    path: ':rails_root/public/system/:class/:attachment/:style/:class_:id.:extension',
    url: '/system/:class/:attachment/:style/:class_:id.:extension',
    default_url: '/assets/:class_missing_:style.png',
    styles: {
      normal: ['960x200#', :jpg]
    },
    convert_options: {all: '-quality 95 -strip'}

  has_attached_file :image,
    path: ':rails_root/public/system/:class/:style/:class_:id.:extension',
    url: '/system/:class/:style/:class_:id.:extension',
    default_url: '/assets/:class_missing_:style.png',
    styles: {
      normal: ['500x500>', :jpg],
      small: ['96x96#', :jpg]
    },
    convert_options: {all: '-quality 95 -strip'}

  auto_permalink :name

  before_validation do
    self.permaname = permaname.andand.parameterize
  end

  validate :check_permaname

  after_create :create_admin_membership, :write_language, :set_minion
  after_validation :set_city

  def check_permaname
    if permaname.present? and permaname_changed? and (Group.find_by_permaname(permaname) or Event.find_by_permaname(permaname))
      errors.add(:permaname, I18n.t('errors.messages.taken'))
    end
  end

  def email_url
    "#{permalink}@#{Settings.host}"
  end

  def add_tag_by_name(name)
    if tag = Tag.find_by_name(name)
      GroupTagging.find_or_create_by_group_id_and_tag_id(id, tag.id)
    end
  end

  def create_admin_membership
    membership = Membership.create group: self
    membership.is_admin = true
    membership.save
  end

  def set_minion
    Minion.set self, :abandoned_group_1
    Minion.set user, :new_group_owner_1 if user.groups.size == 1
  end

  def follow_for(user)
    Follow.find_by_group_id_and_user_id(id, user.id)
  end

  def group_tagging_for(tag)
    GroupTagging.find_by_group_id_and_tag_id(id, tag.id)
  end

  def membership_for(user)
    Membership.find_by_group_id_and_user_id(id, user.id)
  end

  def membership_request_for(user)
    MembershipRequest.find_by_group_id_and_user_id(id, user.id)
  end

  def next_event
    @next_event ||= events.where('start_time > ?', Time.now).order('start_time ASC').first
  end

  def review_for(user)
    Review.find_by_group_id_and_user_id(id, user.id)
  end

  def set_city
    self.city = City.find_or_create_by_name(self.location)
  end

  def tag_tokens=(names)
    ids = []
    names.split(/,\s*/).each do |name|
      ids << Tag.find_or_create_by_name(name).id
    end
    self.tag_ids = ids
  end

  def write_language(code = nil)
    code ||= I18n.locale
    self.language = Language.find_or_create_by_code(code)
    save
  end

  def self.tagged_groups_for(user)
    self.joins(:tags, :language, :city).where('cities.id' => user.city_id, 'languages.code' => I18n.locale, 'tags.id' => user.tags, 'groups.is_closed' => false).select('groups.*, COUNT(group_taggings.tag_id) AS count').group('groups.id').order('count DESC')
  end

  def self.per_page
    20
  end

  def self.recommended_groups_for(user, limit = 10)
    tagged_groups = self.tagged_groups_for(user).limit(limit)
    new_groups = self.joins(:language, :city).where('cities.id' => user.city_id, 'languages.code' => I18n.locale, is_closed: false).order('created_at DESC').limit(limit)
    (tagged_groups + (new_groups - tagged_groups))[0...limit]
  end
end

Group.auto_upgrade!

app/controllers/groups_controller.rb
# encoding: UTF-8

class GroupsController < CommonController
  load_resource
  authorize_resource except: [:index, :show, :events, :images, :members, :tags]

  def show
    @membership_requests = @group.membership_requests.order('created_at ASC').includes(:user).paginate page: params[:page]
    groups_show
  end

  def new
    @group.tags = [Tag.find_by_id(params[:tag_id])] if params[:tag_id]
  end

  def create
    if @group.save
      create_activity @group
      begin
        GroupMailer.creation_for_owner(@group).deliver
      rescue
      end
      User.where(is_admin: true).each do |user|
        begin
          GroupMailer.creation(@group, user).deliver if user.email
        rescue
        end
      end
      @group.tags.each do |tag|
        unless tag.tagging_for(current_user)
          tagging = Tagging.create tag: tag
          create_activity tagging
        end
      end
      redirect_to @group, notice: trfn('Group created.')
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update_attributes params[:group]
      redirect_to @group, notice: trfn('Group updated.')
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to discovery_path, notice: trfn('Group deleted.')
  end

  def events
    @events = @group.events.order('start_time DESC').paginate page: params[:page]
  end

  def images
  end

  def invited
    @group_invitations = @group.group_invitations.order('created_at DESC').page(params[:page])
  end

  def members
    @memberships = @group.memberships.order('is_admin DESC, created_at ASC').includes(:user).paginate page: params[:page]
  end

  def requested_members
    @membership_requests = @group.membership_requests.order('created_at ASC').includes(:user).paginate page: params[:page]
  end

  def set_image
    if image = Image.find_by_id(params[:image_id])
      @group.image = File.open(image.image.path)
      @group.save
    end
    redirect_to @group, notice: trfn('Group profile image changed.')
  end

  def set_header
    if image = Image.find_by_id(params[:image_id])
      @group.header = File.open(image.image.path)
      @group.save
    end
    redirect_to @group, notice: trfn('Group header image changed.')
  end

  def tags
    @tags = @group.tags.order('permalink ASC')
  end

  def waves
    @waves = @group.waves.order('last_changed_at DESC').paginate page: params[:page]
  end

end

app/views/groups/_form.html.haml
= semantic_form_for @group do |f|
  = f.semantic_errors
  = f.inputs :name, :description, :location, :image, :tags, :is_closed
  = f.actions

app/views/groups/_form.html.slim
= easy_form_for @group do |f|
  = f.hidden_field :facebook_uid
  = f.input :name, tr('Name')
  = f.input :description, tr('Description')
  - unless Settings.standalone
    = f.input :location, tr('City')
    = f.input :tag_tokens, tr('Tags'), 'data-pre' => @group.tags.map { |tag| {id: tag.id, name: tag.name} }.to_json
  = f.input :image, tr('Group profile image (we will resize it to 72x72)')
  = f.input :header, tr('Group header image (we will resize it to 945x200)')
  #accordion.panel-group
    .panel.panel-default
      .panel-heading
        a class='panel-title accordion-toggle' data-toggle='collapse' data-parent='#accordion' href='#collapse'
          = tr('More options')
      #collapse.panel-collapse.collapse
        .panel-body
          - if Settings.standalone
            = f.input :location, tr('City')
          = f.input :permaname, tr('Short URL'), prepend: 'http://'+Settings.host+'/'
          = f.input :url, tr('Website URL'), prepend: 'http://'
          = f.input :facebook_url, tr('Facebook URL'), prepend: 'http://'
          = f.input :is_closed, tr('Closed group (admins have to approve membership requests)')
          = f.input :creation_letter_text, tr('Welcome email message to new members')
  = f.action (@group.new_record? ? trl('Create') : trl('Save')), disable_with: (@group.new_record? ? trl('Creating...') : trl('Saving...')), onclick: "_gaq.push(['_trackEvent', 'Create group', 'Group']);"

javascript:
  $('#group_tag_tokens').tokenInput('/tags.json', {
    allowFreeTagging: true,
    allowTabOut: true,
    crossDomain: false,
    tokenValue: 'name',
    preventDuplicates: true,
    prePopulate: $('#group_tag_tokens').data('pre'),
    theme: 'facebook'
  })

app/views/groups/_group.html.slim
= div_for group, class: 'list_item' do
  - if current_user and controller.controller_name == 'discovery'
    .pull-right= link_to '×', uninterests_path(uninterestable_type: 'Group', uninterestable_id: group.id), method: :post, remote: true, class: 'close', title: 'Not interested', confirm: trl('Mark as uninterested?')
  .avatar= link_to(image_tag(group.image.url(:small), alt: group.name, height: 72, width: 72, title: group.name), group)
  .item_content
    - if current_user and membership = group.membership_for(current_user)
      .pull-right
        - if membership.is_admin?
          span.label.label-danger= tr('admin')
        - else
          span.label.label-success= tr('member')
    h3= link_to group.name, group
    p= render group.tags.order('name ASC')
    = render 'groups/tile_menu', group: group
    - if event = group.next_event
      .next_event= render 'groups/next_event', event: event

app/views/groups/_recommended_groups.html.haml
= render Group.recommended_groups_for(current_user)

app/views/groups/_recommended_groups.html.slim
= render Group.recommended_groups_for(current_user)

app/views/groups/_tile_menu.html.slim
p
  = link_to "#{group.members.size} #{tr('members')}", members_group_path(group)
  = dot
  = link_to "#{group.events.size} #{tr('events')}", events_group_path(group)
  = dot
  = link_to "#{group.images.size} #{tr('images')}", images_group_path(group)

app/views/groups/edit.html.slim
.wrapper
  - if can? :destroy, @group
    .pull-right= button_to tr('Delete group'), @group, method: :delete, confirm: trl('Are you sure?'), class: 'btn btn-danger'

  h1= tr('Edit group')

  = render 'form', url: @group

app/views/groups/events.html.slim
= render 'groups/header'

.wrapper
  - if can? :create, Event.new(group: @group)
    .pull-right= link_to tr('New event'), new_group_event_path(@group), class: 'btn btn-default btn-primary', rel: 'modal'

  h2= tr('Events')

  = will_paginate @events
  .list_view= render @events
  = will_paginate @events

app/views/groups/invited.html.slim
- unless modal_request?
  = render 'groups/header'

.wrapper
  .button-menu
    = link_to tr('Invite friends'), new_group_group_invitation_path(@group), class: 'btn btn-default', rel: 'modal'

  h2= tr('Already invited')

  = will_paginate @group_invitations

  table.table
    - @group_invitations.each do |group_invitation|
      tr
        td
          - if group_invitation.invited_user.present?
            = user_link group_invitation.invited_user
          - else
            = group_invitation.email
        td.right_aligned= l(group_invitation.created_at)

  = will_paginate @group_invitations

app/views/groups/members.html.slim
= render 'groups/header'

.wrapper

  .button-menu
    = link_to tr('Invite friends'), new_group_group_invitation_path(@group), class: 'btn btn-default btn-primary', rel: 'modal'

  h2= tr('Members')

  .list_view= render @memberships
  = will_paginate @memberships

app/views/groups/new.html.slim
.wrapper
  h1= tr('Start a meetup group')

  = render 'form', url: @group

app/views/groups/requested_members.html.slim
- unless modal_request?
  = render 'groups/header'

.wrapper
  h2= tr('Requests')
  .list_view= render @membership_requests
  = will_paginate @membership_requests

app/views/groups/tags.html.slim
.wrapper
  h1= tr("Pick some new interests")
  p= tr("We'll notify you about other meetups that match the interests you select")

  - @tags.each do |tag|
    = render 'taggings/text_button', tag: tag

  hr

  p
    =' link_to tr('Save'), @group, class: 'btn btn-primary'
    =' link_to tr('Cancel'), @group, class: 'btn btn-default'

app/views/groups/users.html.slim
= render 'header'

.row
  .span8
    .wrapper
      - if current_user and not (users = @group.members.where('users.uid' => current_user.facebook_friend_ids).order('users.permalink ASC')).empty?
        h3= tr('Facebook friends')
        p= render 'users/user_avatars', :users => users
      h3= tr('Members')
      .list_view= render @memberships
      = will_paginate @memberships
  .span4
    - if current_user
      .wrapper
        p
          =' link_to 'Ismerősök hozzáadása', new_group_group_invitation_path(@group), :class => 'btn btn-primary', :rel => 'facebox'
          = link_to '→ Meghívottak', invited_group_path(@group)
    .wrapper
      - unless (users = @group.admins.order('memberships.created_at ASC')).empty?
        h3= tr('Admins')
        p= render 'users/user_avatars', :users => users