config/routes.rb
Openmeetup::Application.routes.draw do

  # mount WillFilter::Engine => '/will_filter'
  # mount Tr8n::Engine => '/tr8n'

  mount AdminMailer::Preview => '/admin_mailer/mail_view'
  mount CommentMailer::Preview => '/comment_mailer/mail_view'
  mount EventInvitationMailer::Preview => '/event_invitation_mailer/mail_view'
  mount EventMailer::Preview => '/event_mailer/mail_view'
  mount FriendshipMailer::Preview => '/friendship_mailer/mail_view'
  mount GroupInvitationMailer::Preview => '/group_invitation_mailer/mail_view'
  mount GroupMailer::Preview => '/group_mailer/mail_view'
  mount LetterMailer::Preview => '/letter_mailer/mail_view'
  mount MinionMailer::Preview => '/minion_mailer/mail_view'
  mount MembershipRequestMailer::Preview => '/membership_request_mailer/mail_view'
  mount ParticipationMailer::Preview => '/participation_mailer/mail_view'
  mount PostMailer::Preview => '/post_mailer/mail_view'
  mount UserMailer::Preview => '/user_mailer/mail_view'
  mount VoteMailer::Preview => '/vote_mailer/mail_view'
  mount WaveMailer::Preview => '/wave_mailer/mail_view'

  namespace :admin do
    resources :users
  end

  resources :activities do
    resources :comments, shallow: true
  end

  resources :cities do
    member do
      get :search
    end
    collection do
      post :jump
    end
  end

  resources :feedbacks

  resources :friendships do
    member do
      post :decline
      post :set_confirmed
      post :set_delayed
    end
  end

  resources :groups do
    member do
      get :events
      get :images
      get :invited
      get :members
      get :requested_members
      post :set_image
      post :set_header
      get :tags
      get :waves
    end
    resources :posts, shallow: true
    resources :events, shallow: true do
      member do
        get :actual
        get :images
        get :invited
        get :map
        get :participations
        get :reviews
        get :users
        get :users_with_emails
      end
      resources :absences, shallow: true do
        collection do
          get :set
        end
      end
      resources :comments, shallow: true
      resources :event_invitations, shallow: true
      resources :images, shallow: true do
        collection do
          post :upload
        end
      end
      resources :participations, shallow: true do
        member do
          post :checkin
        end
        collection do
          get :set
        end
      end
      resources :posts, shallow: true
      resources :questions, shallow: true
      resources :reviews, shallow: true
    end
    resources :group_invitations, shallow: true
    resources :images, shallow: true do
      collection do
        post :upload
      end
    end
    resources :membership_requests, shallow: true do
      member do
        put :confirm
      end
    end
    resources :memberships, shallow: true do
      collection do
        get :set
      end
      member do
        put :set_admin
        put :unset_admin
      end
    end
    resources :tags, shallow: true do
      resources :taggings, shallow: true do
        collection do
          post :set
        end
      end
    end
  end

  resources :images do
    member do
      get :next
      get :previous
    end
    resources :comments, shallow: true
  end

  resources :interests do
    resources :interest_taggings, shallow: true
  end

  resources :letter_templates do
    member do
      post :create_letter
    end
  end

  resources :letters do
    member do
      post :mail
      post :mailtest
    end
  end

  resources :notifications

  resources :passwords

  resources :posts do
    resources :comments, shallow: true
  end

  resources :settings

  resources :tags

  resources :uninterests, only: [:index, :create, :destroy]

  resource :user_sessions

  resources :users do
    resources :friendships, shallow: true
    collection do
      get :request_invite
      get :recommendations
      get :validate_email
    end
    member do
      get :calendar
      get :edit_city
      get :facebook_groups
      get :friend_requests
      get :groups
      get :set_admin
      post :set_admin
      get :unset_admin
      post :unset_admin
      post :set_avatar
      post :set_header
      get :settings
      get :tags
      get :waves
    end
  end

  resources :votes, only: [:index] do
    collection do
      post :set
    end
  end

  resources :waves do
    resources :wave_items
  end

  match '/about' => 'root#about', as: :about
  match '/crash' => 'root#crash', as: :crash
  match '/search' => 'search#index', as: :search
  match '/restricted_access' => 'root#restricted_access', as: :restricted_access
  match '/terms' => 'root#terms', as: :terms
  match '/pricing' => 'root#pricing', as: :pricing
  match '/privacy' => 'root#privacy', as: :privacy

  match '/discovery' => 'discovery#index', as: :discovery

  match '/system-settings' => 'dashboard#index', as: :system
  match '/reload' => 'dashboard#reload', as: :reload
  match '/download_database' => 'dashboard#download_database', as: :download_database
  match '/download_translations' => 'dashboard#download_translations', as: :download_translations

  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'
  match '/sign_in' => 'root#sign_in', as: :sign_in
  match '/sign_in_with_email' => 'users#new', as: :sign_in_with_email
  match '/sign_out' => 'user_sessions#destroy', as: :sign_out

  root to: 'root#index'
  match ':controller(/:action(/:id))(.:format)'
  match '/:id' => 'root#undefined', as: :undefined
end

app/models/wave.rb
# encoding: UTF-8

class Wave < ActiveRecord::Base
  key :subject
  key :last_changed_at, as: :datetime
  timestamps

  belongs_to :group
  belongs_to :event
  belongs_to :user
  has_many :wave_items, dependent: :destroy
  has_many :wave_memberships, dependent: :destroy
  has_many :wave_members, through: :wave_memberships, source: :user
  has_many :wave_notes, dependent: :destroy

  attr_accessor :body, :recipient_id
  validates :subject, :body, presence: true

  after_create :change!, :create_initial_membership, :add_recipients


  def add_recipients
    group.members.each { |user| add_wave_member(user) } if group
    event.participants.each { |user| add_wave_member(user) } if event
  end

  def add_wave_member(user)
    WaveMembership.find_or_create_by_wave_id_and_user_id(id, user.id)
  end

  def change!
    update_attribute :last_changed_at, Time.now
  end

  def create_initial_membership
    WaveMembership.create wave_id: id, user_id: self.user.id
  end

  def wave_membership_for(user)
    WaveMembership.find_by_wave_id_and_user_id(id, user.id)
  end

  def wave_note_for(user)
    WaveNote.find_by_wave_id_and_user_id(id, user.id)
  end

  def self.per_page
    10
  end
end

Wave.auto_upgrade!

app/controllers/waves_controller.rb
# encoding: UTF-8

class WavesController < CommonController
  load_resource
  authorize_resource

  def index
    @waves = Wave.order('last_changed_at DESC').paginate joins: :wave_memberships, conditions: {'wave_memberships.user_id' => current_user.id, 'wave_memberships.is_archived' => false, 'wave_memberships.is_deleted' => false}, include: [:users, :wave_notes], page: params[:page]
  end

  def show
    @wave = Wave.find(params[:id])
    if @wave.wave_membership_for(current_user) or @wave.user == current_user
      if wave_note = WaveNote.find_by_wave_id_and_user_id(@wave.id, current_user.id)
        @note_created_at = wave_note.created_at
        wave_note.destroy
        current_user.reload
      end
      @wave_items = @wave.wave_items.order('created_at DESC').includes(:user).paginate page: params[:page]
    else
      flash[:alert] = 'Nem tekintheted meg ezt a folyamot!'
      redirect_to waves_url
    end
  end

  def new
    @recipient = User.find_by_id(params[:recipient_id]) if params[:recipient_id].present?
  end

  def create
    @wave = Wave.new(params[:wave])
    if @wave.save
      if @wave.recipient_id.present? and user = User.find_by_id(@wave.recipient_id)
        @wave.add_wave_member(user)
      end
      wave_item = WaveItem.create(wave_id: @wave.id, body: @wave.body)
      redirect_to @wave
    else
      render :new
    end
  end

  def all
    @waves = Wave.order('last_changed_at DESC').paginate joins: :wave_memberships, conditions: {'wave_memberships.user_id' => current_user.id, 'wave_memberships.is_deleted' => false}, include: [:users, :wave_notes], page: params[:page]
    render :index
  end
end

app/views/waves/_sidebar.html.slim
ul.sidemenu
  = menu_item 'Friss üzenetek', wave_notes_path, controller: 'wave_notes', action: 'index'
  = menu_item 'Bejövő üzenetek', waves_path, controller: 'waves', action: 'index'
  = menu_item 'Csillagozott üzenetek', starred_waves_path, controller: 'waves', action: 'starred'
  = menu_item 'Saját üzenetek', own_waves_path, controller: 'waves', action: 'own'
  = menu_item 'Összes üzenet', all_waves_path, controller: 'waves', action: 'all'
- if can? :create, Wave
  .sidelinks
    = link_to 'Új üzenet', new_wave_path, class: 'action'

#online

app/views/waves/_wave.html.slim
= div_for wave, class: 'list_item clearfix' do
  p.pull-right
    - wave.wave_members.each do |user|
      = user_avatar user
  h3= link_to wave.subject, wave
  =' wave.wave_items.size
  =' tr('messages')
  span.date=' timeago_tag wave.last_changed_at
  - if wave.group
    ' →
    = link_to wave.group.name, wave.group
  - if wave.event
    ' →
    = link_to wave.event.title, wave.event

app/views/waves/new.html.slim
.wrapper
  = semantic_form_for @wave do |f|
    = hidden_field_tag 'wave[group_id]', params[:group_id]
    = hidden_field_tag 'wave[event_id]', params[:event_id]
    = f.inputs do
      = f.input :recipient_id, label: trl('To')
      = f.input :subject
      = f.input :body, as: :text
    = f.actions do
      = f.action :submit, label: trl('Send')

javascript:
  $('#wave_recipient_id').tokenInput('/users.json', {
    allowFreeTagging: true,
    allowTabOut: true,
    crossDomain: false,
    tokenValue: 'id',
    preventDuplicates: true,
    prePopulate: #{(@recipient ? [{id: @recipient.id, name: @recipient.name}] : nil).to_json.html_safe},
    tokenLimit: 1,
    theme: 'facebook'
  })

app/views/waves/show.html.slim
.row
  .col-lg-4
    .wrapper
      - if @wave.group or @wave.event
        .breadcrumbs.clearfix
          - if @wave.group
            = link_to @wave.group.name, @wave.group
          - if @wave.event
            = link_to @wave.event.title, @wave.event

      h1= @wave.subject

      p= render 'users/user_avatars', users: @wave.wave_members
  .col-lg-8
    .wrapper
      = semantic_form_for @wave.wave_items.build, url: wave_wave_items_path(@wave) do |f|
        = f.inputs do
          = f.input :body, label: false
        = f.actions do
          = f.action :submit, label: trl('Reply')
      .list_view= render @wave_items